[package]
name = "table_macro"
version = "0.1.0"
authors = ["Alex Grinman <me@alexgr.in>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
internal = { path = "../internal"}
